# Generated by Django 3.0.8 on 2020-07-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsurveillance',
            name='CameraID',
            field=models.CharField(default=2820040001, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='CameraID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
