# Generated by Django 3.0.8 on 2020-07-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20200727_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrto',
            name='useless',
            field=models.CharField(default='HI', max_length=10),
        ),
    ]
