# Generated by Django 3.0.8 on 2020-07-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_carrto_useless'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrto',
            name='useless',
        ),
    ]
